### ISSUE TITLE
Automate Onboarding to Cluster via CLI

### ISSUE THREAD

**Issue by HumairAK** [operate-first/opfcli#24]
The steps [here](https://www.operate-first.cloud/users/support/docs/onboarding_to_cluster.md) should be automated via the opfcli. The tricky part would be handling pgp keys. 

Starting out the opfcli should take a config file that essentially imitates the fields from the onboarding issue templated found [here](https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=onboarding_to_cluster.md&title=). 

```yaml
onboarding_template:
  team_name: example_team
  list_of_namespaces:
    - name: ns_1
      quota: medium
      enable_monitoring: true
    - name: ns_2
      quota: large
      enable_monitoring: false
  list_of_users:
    - user_1
    - user_2
  project_description: "example description"
  env: MOC
  cluster: ZERO
  optional_pgp_keys:
    - key_1
    - key_2
```

Then for onboarding we can pass it to the cli like so: 

```bash
$ opfcli onboard cluster --onboard-config config.yaml
```

`cluster` should be a subcommand of `onboard` which should be a subcommand of `opfcli` (eventually want to add other onboarding subcommands like `opfcli onboard argocd`). 

Currently some of the logic for this process is already implemented, so this sub-command should just be calling that logic. Then add the additional bits for adding the resources to the appropriate cluster/env.

The next step following this issue will be to eventually have people fill out a yaml/form and have a bot perform the PR by running this cli command.
