### ISSUE TITLE
Update precommit configuration for Go source

### ISSUE THREAD

**Issue by larsks** [operate-first/opfcli#3]
We should update the pre-commit configuration using e.g. https://github.com/dnephin/pre-commit-golang/. We'd probably want something like:

```
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
```

This would require adding some tools to our CI image
